project_id = "qfnptknanxyfxvcuhgck"

[functions.check-deposit-rental-day]
verify_jwt = false

[functions.check-handover-day]
verify_jwt = false

[functions.check-return-day]
verify_jwt = false

[functions.check-return-2days]
verify_jwt = false

[functions.check-upcoming-rentals]
verify_jwt = false

[functions.check-rental-2days]
verify_jwt = false

[functions.check-expiring-insurance]
verify_jwt = false

[functions.check-expiring-inspection]
verify_jwt = false

[functions.check-deposit-3days]
verify_jwt = false

[functions.check-deposit-5days]
verify_jwt = false

[functions.send-invoice-file-notification]
verify_jwt = false

[functions.check-rental-start-day]
verify_jwt = false

[functions.telegram-update-deposit]
verify_jwt = false

[functions.notify-driver-submission]
verify_jwt = false

[functions.check-payment-due-7days]
verify_jwt = false

[functions.check-payment-overdue]
verify_jwt = false

[functions.check-final-invoice-due]
verify_jwt = false

[functions.export-data]
verify_jwt = false